"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['game.py']
DATA_FILES = ['assets']
OPTIONS = {'iconfile': 'assets/icon/icon'}

setup(
    app=APP,
    name='Gun Mayhem',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
